version: '3.7'

networks:
    lwg-backend:

services:
    php:
        container_name: symfony-api
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        networks:
            - "lwg-backend"

    nginx:
        build:
            context: ./nginx
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        ports:
            - "80:80"
        networks:
            - "lwg-backend"
        env_file:
            - .env.nginx.local

    ###> doctrine/doctrine-bundle ###
    database:
        ports:
            - "5432"
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        networks:
            - "lwg-backend"
    ###< doctrine/doctrine-bundle ###
