version: '3.7'

networks:
    lwg-backend:

services:
    php:
        container_name: backend
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        networks:
            - "lwg-backend"

    nginx:
        build:
            context: ./nginx
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        ports:
            - "8080:80"
        networks:
            - "lwg-backend"
        env_file:
            - .env.nginx.local

    ###> doctrine/doctrine-bundle ###
    localhost:
        container_name: lwg-database
        ports:
            - "5432"
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        networks:
            - "lwg-backend"
    ###< doctrine/doctrine-bundle ###

    mailhog:
        container_name: lwg-mailhog
        image: mailhog/mailhog
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - "lwg-backend"
